name: Main
version: 1.0
main: com.nohaxjustprogram.genbuckets.Main
authors: [NoHaxJustProgram]
description: A simple genbuckets plugin for minecraft spigot!
website: https://github.com/NoHaxJustProgram?tab=repositories

commands:
  genbucket:
    description: Gives a genbucket
    usage: /genbucekt
    aliases: [genb, bucketgen, gen]